"""The one interface both engines implement."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

import pyarrow as pa

from src.lakehouse.schemas import TableDef


@runtime_checkable
class LakehouseEngine(Protocol):
    def create_table(self, table_def: TableDef) -> None: ...
    def table_exists(self, ident: str) -> bool: ...
    def arrow_schema(self, ident: str) -> pa.Schema: ...
    def append(self, ident: str, data: pa.Table) -> None: ...
    def overwrite(self, ident: str, data: pa.Table) -> None: ...
    def scan_arrow(self, ident: str, snapshot_id: int | None = None) -> pa.Table: ...
    def snapshots(self, ident: str) -> list[int]: ...
    def snapshot_row_counts(self, ident: str) -> list[int]: ...
    def snapshot_details(self, ident: str) -> list[dict]: ...
    def schema_history(self, ident: str) -> list[dict]: ...
    def sql(self, query: str, tables: dict[str, str]) -> pa.Table: ...
